import {
  DetailRecentTransactionsCard,
  type TransactionItem,
} from "../financecards";

export function Logs() {
  const transactions: TransactionItem[] = [
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      title: "Swiggy",
      amount: "₹250",
      mode: "expense",
      account: "Cash",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
    {
      amount: "₹18,000",
      mode: "income",
      account: "Bank",
      category: "Salary",
    },
  ];
  return (
    <div>
      <h2 className="text-3xl font-light mb-4">Logs</h2>
      <DetailRecentTransactionsCard data={transactions} />
    </div>
  );
}
